# Generated by Django 4.2 on 2023-05-12 08:44

from django.db import migrations, models
import django.utils.timezone
from datetime import datetime

now = datetime.now()
date_time_string = now.strftime("%Y-%m-%d %H:%M:%S")


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_right_rename_child_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='left',
            old_name='name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='right',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='left',
            name='age',
        ),
        migrations.RemoveField(
            model_name='right',
            name='age',
        ),
        migrations.AddField(
            model_name='left',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=date_time_string),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='firstname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='referal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=date_time_string),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='firstname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='referal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
