# Generated by Django 4.2 on 2023-05-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_name_left_city_rename_name_right_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='left',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.left'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='right',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.right'),
        ),
        migrations.AlterField(
            model_name='left',
            name='referal',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='right',
            name='referal',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
