# Generated by Django 4.2 on 2023-05-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_userprofile_left_userprofile_right_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='left',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='right',
        ),
    ]
