# Generated by Django 4.2 on 2023-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='left',
            name='package',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='right',
            name='package',
            field=models.CharField(default='', max_length=100),
        ),
    ]
